### ISSUE TITLE
Plugin does not work on release 10.9 and above.

### ISSUE THREAD

**Issue by perhapsjames** [bennystarfighter/jellyfin-subtitle-sorter#1]
The plugin does not work on Jellyfin release v10.9.0 and newer. 

Will the plugin be updated or is the project no longer maintained?

Thanks

**Comment by bennystarfighter** [comment]
Hey, thanks for notifying. I'm not doing any active work on the plugin since i feel it's easily replaced with other better solutions such as sonarr + bazarr for an example. But i've updated it now to the latest jellyfin api. Should be good for a couple of upcoming jellyfin versions.

Checkout the latest release here or update in jellyfin. 
[Subtitle-Sorter v1.0.0.5](https://github.com/bennystarfighter/jellyfin-subtitle-sorter/releases/tag/v1.0.0.5)

I tested in in my development environment but please get back to me @perhapsjames if it's working as usual for you.

**Comment by perhapsjames** [comment]
Tested the update. Works nicely.

Thanks for the work on this plugin, I'll look into sonarr+bazarr. 

Thanks again..
